version: '3'

services:
  master:
    image: lewuathe/hadoop-master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"
  slave1:
    image: lewuathe/hadoop-slave
    container_name: "slave1"
    depends_on:
      - master
    ports:
      - "9901:9864"
      - "8041:8042"
  slave2:
    image: lewuathe/hadoop-slave
    container_name: "slave2"
    depends_on:
      - master
    ports:
      - "9902:9864"
      - "8042:8042"
  slave3:
    image: lewuathe/hadoop-slave
    container_name: "slave3"
    depends_on:
      - master
    ports:
      - "9903:9864"
      - "8043:8042"
  slave4:
    image: lewuathe/hadoop-slave
    container_name: "slave4"
    depends_on:
      - master
    ports:
      - "9904:9864"
      - "8044:8042"    
  slave5:
    image: lewuathe/hadoop-slave
    container_name: "slave5"
    depends_on:
      - master
    ports:
      - "9905:9864"
      - "8045:8042"
